package net.aicoder.exsys.module.entity;

// Generated 2015-10-31 11:27:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TDevEntKey generated by hbm2java
 */
@Entity
//@Table(name = "t_dev_ent_key", catalog = "db_jeap_dev", uniqueConstraints = @UniqueConstraint(columnNames = {
//		"ent_id", "id" }))
@Table(name = "t_dev_ent_key", uniqueConstraints = @UniqueConstraint(columnNames = {"ent_id", "id" }))
public class TDevEntKey implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String id;
	private TDevEntity TDevEntity;
	private String type;
	private String code;
	private String name;
	private Integer seq;
	private String uqFlag;
	private String clFlag;
	private String orderFlag;
	private String notes;
	private String CUid;
	private String CName;
	private Date CTime;
	private String MUid;
	private String MName;
	private Date MTime;
	private List<TDevEntRelation> TDevEntRelationsForSrcKeyId = new ArrayList<TDevEntRelation>(
			0);
	private List<TDevKeyAttribute> TDevKeyAttributes = new ArrayList<TDevKeyAttribute>(
			0);
	private List<TDevEntRelation> TDevEntRelationsForDestKeyId = new ArrayList<TDevEntRelation>(
			0);

	public TDevEntKey() {
	}

/*	public TDevEntKey(String id, TDevEntity TDevEntity, String type,
			String code, String name) {
		this.id = id;
		this.TDevEntity = TDevEntity;
		this.type = type;
		this.code = code;
		this.name = name;
	}

	public TDevEntKey(String id, TDevEntity TDevEntity, String type,
			String code, String name, Integer seq, String uqFlag,
			String clFlag, String orderFlag, String notes, String CUid,
			String CName, Date CTime, String MUid, String MName, Date MTime,
			Set<TDevEntRelation> TDevEntRelationsForSrcKeyId,
			Set<TDevKeyAttribute> TDevKeyAttributes,
			Set<TDevEntRelation> TDevEntRelationsForDestKeyId) {
		this.id = id;
		this.TDevEntity = TDevEntity;
		this.type = type;
		this.code = code;
		this.name = name;
		this.seq = seq;
		this.uqFlag = uqFlag;
		this.clFlag = clFlag;
		this.orderFlag = orderFlag;
		this.notes = notes;
		this.CUid = CUid;
		this.CName = CName;
		this.CTime = CTime;
		this.MUid = MUid;
		this.MName = MName;
		this.MTime = MTime;
		this.TDevEntRelationsForSrcKeyId = TDevEntRelationsForSrcKeyId;
		this.TDevKeyAttributes = TDevKeyAttributes;
		this.TDevEntRelationsForDestKeyId = TDevEntRelationsForDestKeyId;
	}*/

	@Id
	@GeneratedValue(generator = "paymentableGenerator")
	//@GenericGenerator(name = "paymentableGenerator", strategy = "uuid")
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ent_id", nullable = false)
	public TDevEntity getTDevEntity() {
		return this.TDevEntity;
	}

	public void setTDevEntity(TDevEntity TDevEntity) {
		this.TDevEntity = TDevEntity;
	}

	@Column(name = "[type]", nullable = false, length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "[code]", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "[name]", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "seq")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "uq_flag", length = 10)
	public String getUqFlag() {
		return this.uqFlag;
	}

	public void setUqFlag(String uqFlag) {
		this.uqFlag = uqFlag;
	}

	@Column(name = "cl_flag", length = 10)
	public String getClFlag() {
		return this.clFlag;
	}

	public void setClFlag(String clFlag) {
		this.clFlag = clFlag;
	}

	@Column(name = "order_flag", length = 10)
	public String getOrderFlag() {
		return this.orderFlag;
	}

	public void setOrderFlag(String orderFlag) {
		this.orderFlag = orderFlag;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "c_uid", length = 50)
	public String getCUid() {
		return this.CUid;
	}

	public void setCUid(String CUid) {
		this.CUid = CUid;
	}

	@Column(name = "c_name", length = 50)
	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", length = 19)
	public Date getCTime() {
		return this.CTime;
	}

	public void setCTime(Date CTime) {
		this.CTime = CTime;
	}

	@Column(name = "m_uid", length = 50)
	public String getMUid() {
		return this.MUid;
	}

	public void setMUid(String MUid) {
		this.MUid = MUid;
	}

	@Column(name = "m_name", length = 50)
	public String getMName() {
		return this.MName;
	}

	public void setMName(String MName) {
		this.MName = MName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", length = 19)
	public Date getMTime() {
		return this.MTime;
	}

	public void setMTime(Date MTime) {
		this.MTime = MTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDevEntKeyBySrcKeyId")
	public List<TDevEntRelation> getTDevEntRelationsForSrcKeyId() {
		return this.TDevEntRelationsForSrcKeyId;
	}

	public void setTDevEntRelationsForSrcKeyId(
			List<TDevEntRelation> TDevEntRelationsForSrcKeyId) {
		this.TDevEntRelationsForSrcKeyId = TDevEntRelationsForSrcKeyId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDevEntKey")
	//@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	public List<TDevKeyAttribute> getTDevKeyAttributes() {
		return this.TDevKeyAttributes;
	}

	public void setTDevKeyAttributes( List<TDevKeyAttribute> TDevKeyAttributes) {
		this.TDevKeyAttributes = TDevKeyAttributes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDevEntKeyByDestKeyId")
	public List<TDevEntRelation> getTDevEntRelationsForDestKeyId() {
		return this.TDevEntRelationsForDestKeyId;
	}

	public void setTDevEntRelationsForDestKeyId(
			List<TDevEntRelation> TDevEntRelationsForDestKeyId) {
		this.TDevEntRelationsForDestKeyId = TDevEntRelationsForDestKeyId;
	}

}
