package net.aicoder.exsys.module.entity;

// Generated 2015-10-31 11:27:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TDevKeyAttribute generated by hbm2java
 */
@Entity
//@Table(name = "t_dev_key_attribute", catalog = "db_jeap_dev", uniqueConstraints = @UniqueConstraint(columnNames = {
//		"key_id", "attr_id" }))
@Table(name = "t_dev_key_attribute", uniqueConstraints = @UniqueConstraint(columnNames = {"key_id", "attr_id" }))
public class TDevKeyAttribute implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	

	private String id;
	private TDevAttribute TDevAttribute;
	private TDevEntKey TDevEntKey;
	private String name;
	private Integer seq;
	private String orderFlag;
	private String notes;
	private String CUid;
	private String CName;
	private Date CTime;
	private String MUid;
	private String MName;
	private Date MTime;

	public TDevKeyAttribute() {
	}

/*	public TDevKeyAttribute(String id, TDevAttribute TDevAttribute,
			TDevEntKey TDevEntKey, String name) {
		this.id = id;
		this.TDevAttribute = TDevAttribute;
		this.TDevEntKey = TDevEntKey;
		this.name = name;
	}

	public TDevKeyAttribute(String id, TDevAttribute TDevAttribute,
			TDevEntKey TDevEntKey, String name, Integer seq, String orderFlag,
			String notes, String CUid, String CName, Date CTime, String MUid,
			String MName, Date MTime) {
		this.id = id;
		this.TDevAttribute = TDevAttribute;
		this.TDevEntKey = TDevEntKey;
		this.name = name;
		this.seq = seq;
		this.orderFlag = orderFlag;
		this.notes = notes;
		this.CUid = CUid;
		this.CName = CName;
		this.CTime = CTime;
		this.MUid = MUid;
		this.MName = MName;
		this.MTime = MTime;
	}*/

	@Id
	@GeneratedValue(generator = "paymentableGenerator")
	//@GenericGenerator(name = "paymentableGenerator", strategy = "uuid")
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attr_id", nullable = false)
	public TDevAttribute getTDevAttribute() {
		return this.TDevAttribute;
	}

	public void setTDevAttribute(TDevAttribute TDevAttribute) {
		this.TDevAttribute = TDevAttribute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "key_id", nullable = false)
	public TDevEntKey getTDevEntKey() {
		return this.TDevEntKey;
	}

	public void setTDevEntKey(TDevEntKey TDevEntKey) {
		this.TDevEntKey = TDevEntKey;
	}

	@Column(name = "[name]", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "seq")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "order_flag", length = 10)
	public String getOrderFlag() {
		return this.orderFlag;
	}

	public void setOrderFlag(String orderFlag) {
		this.orderFlag = orderFlag;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "c_uid", length = 50)
	public String getCUid() {
		return this.CUid;
	}

	public void setCUid(String CUid) {
		this.CUid = CUid;
	}

	@Column(name = "c_name", length = 50)
	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", length = 19)
	public Date getCTime() {
		return this.CTime;
	}

	public void setCTime(Date CTime) {
		this.CTime = CTime;
	}

	@Column(name = "m_uid", length = 50)
	public String getMUid() {
		return this.MUid;
	}

	public void setMUid(String MUid) {
		this.MUid = MUid;
	}

	@Column(name = "m_name", length = 50)
	public String getMName() {
		return this.MName;
	}

	public void setMName(String MName) {
		this.MName = MName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", length = 19)
	public Date getMTime() {
		return this.MTime;
	}

	public void setMTime(Date MTime) {
		this.MTime = MTime;
	}

}
