package net.aicoder.exsys.module.entity;

// Generated 2015-10-31 11:27:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
//import javax.persistence.GenerationType;

//import org.hibernate.annotations.GenericGenerator;


/**
 * TDevAttribute generated by hbm2java
 */
@Entity
//@Table(name = "t_dev_attribute", catalog = "db_jeap_dev", uniqueConstraints = @UniqueConstraint(columnNames = {
//		"ent_id", "id" }))
@Table(name = "t_dev_attribute", uniqueConstraints = @UniqueConstraint(columnNames = {"ent_id", "id" }))
public class TDevAttribute implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	

	private String id;
	private TDevEntity TDevEntity;
	private String code;
	private String name;
	private Integer seq;
	private String dataType;
	private Integer length;
	private Integer precise;
	private Integer scale;
	private String nnFlag;
	private String pkFlag;
	private String uqFlag;
	private String aiFlag;
	private String dftValue;
	private String notes;
	private String CUid;
	private String CName;
	private Date CTime;
	private String MUid;
	private String MName;
	private Date MTime;
	private List<TDevErAttribute> TDevErAttributesForDestAttrId = new ArrayList<TDevErAttribute>(
			0);
	private List<TDevKeyAttribute> TDevKeyAttributes = new ArrayList<TDevKeyAttribute>(
			0);
	private List<TDevErAttribute> TDevErAttributesForSrcAttrId = new ArrayList<TDevErAttribute>(
			0);

	public TDevAttribute() {
	}

/*	public TDevAttribute(String id, TDevEntity TDevEntity, String code,
			String name, String dataType) {
		this.id = id;
		this.TDevEntity = TDevEntity;
		this.code = code;
		this.name = name;
		this.dataType = dataType;
	}

	public TDevAttribute(String id, TDevEntity TDevEntity, String code,
			String name, Integer seq, String dataType, Integer length,
			Integer precision, Integer scale, String nnFlag, String pkFlag,
			String uqFlag, String aiFlag, String default_, String notes,
			String CUid, String CName, Date CTime, String MUid, String MName,
			Date MTime, List<TDevErAttribute> TDevErAttributesForDestAttrId,
			Set<TDevKeyAttribute> TDevKeyAttributes,
			Set<TDevErAttribute> TDevErAttributesForSrcAttrId) {
		this.id = id;
		this.TDevEntity = TDevEntity;
		this.code = code;
		this.name = name;
		this.seq = seq;
		this.dataType = dataType;
		this.length = length;
		this.precision = precision;
		this.scale = scale;
		this.nnFlag = nnFlag;
		this.pkFlag = pkFlag;
		this.uqFlag = uqFlag;
		this.aiFlag = aiFlag;
		this.default_ = default_;
		this.notes = notes;
		this.CUid = CUid;
		this.CName = CName;
		this.CTime = CTime;
		this.MUid = MUid;
		this.MName = MName;
		this.MTime = MTime;
		this.TDevErAttributesForDestAttrId = TDevErAttributesForDestAttrId;
		this.TDevKeyAttributes = TDevKeyAttributes;
		this.TDevErAttributesForSrcAttrId = TDevErAttributesForSrcAttrId;
	}*/

	@Id
	@GeneratedValue(generator = "paymentableGenerator")
	//@GenericGenerator(name = "paymentableGenerator", strategy = "uuid")
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ent_id", nullable = false)
	public TDevEntity getTDevEntity() {
		return this.TDevEntity;
	}

	public void setTDevEntity(TDevEntity TDevEntity) {
		this.TDevEntity = TDevEntity;
	}

	@Column(name = "[code]", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "[name]", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "seq")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "data_type", nullable = false, length = 50)
	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	@Column(name = "length")
	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	//@Column(name = "precise")
	@Column(name = "[precision]") 
	public Integer getPrecise() {
		return this.precise;
	}

	public void setPrecise(Integer precision) {
		this.precise = precision;
	}

	@Column(name = "scale")
	public Integer getScale() {
		return this.scale;
	}

	public void setScale(Integer scale) {
		this.scale = scale;
	}

	@Column(name = "nn_flag", length = 10)
	public String getNnFlag() {
		return this.nnFlag;
	}

	public void setNnFlag(String nnFlag) {
		this.nnFlag = nnFlag;
	}

	@Column(name = "pk_flag", length = 10)
	public String getPkFlag() {
		return this.pkFlag;
	}

	public void setPkFlag(String pkFlag) {
		this.pkFlag = pkFlag;
	}

	@Column(name = "uq_flag", length = 10)
	public String getUqFlag() {
		return this.uqFlag;
	}

	public void setUqFlag(String uqFlag) {
		this.uqFlag = uqFlag;
	}

	@Column(name = "ai_flag", length = 10)
	public String getAiFlag() {
		return this.aiFlag;
	}

	public void setAiFlag(String aiFlag) {
		this.aiFlag = aiFlag;
	}

	@Column(name = "dft_value")
	public String getDftValue() {
		return this.dftValue;
	}

	public void setDftValue(String dftValue) {
		this.dftValue = dftValue;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "c_uid", length = 50)
	public String getCUid() {
		return this.CUid;
	}

	public void setCUid(String CUid) {
		this.CUid = CUid;
	}

	@Column(name = "c_name", length = 50)
	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", length = 19)
	public Date getCTime() {
		return this.CTime;
	}

	public void setCTime(Date CTime) {
		this.CTime = CTime;
	}

	@Column(name = "m_uid", length = 50)
	public String getMUid() {
		return this.MUid;
	}

	public void setMUid(String MUid) {
		this.MUid = MUid;
	}

	@Column(name = "m_name", length = 50)
	public String getMName() {
		return this.MName;
	}

	public void setMName(String MName) {
		this.MName = MName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", length = 19)
	public Date getMTime() {
		return this.MTime;
	}

	public void setMTime(Date MTime) {
		this.MTime = MTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDevAttributeByDestAttrId")
	public List<TDevErAttribute> getTDevErAttributesForDestAttrId() {
		return this.TDevErAttributesForDestAttrId;
	}

	public void setTDevErAttributesForDestAttrId(
			List<TDevErAttribute> TDevErAttributesForDestAttrId) {
		this.TDevErAttributesForDestAttrId = TDevErAttributesForDestAttrId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDevAttribute")
	public List<TDevKeyAttribute> getTDevKeyAttributes() {
		return this.TDevKeyAttributes;
	}

	public void setTDevKeyAttributes( List<TDevKeyAttribute> TDevKeyAttributes) {
		this.TDevKeyAttributes = TDevKeyAttributes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDevAttributeBySrcAttrId")
	public List<TDevErAttribute> getTDevErAttributesForSrcAttrId() {
		return this.TDevErAttributesForSrcAttrId;
	}

	public void setTDevErAttributesForSrcAttrId(
			List<TDevErAttribute> TDevErAttributesForSrcAttrId) {
		this.TDevErAttributesForSrcAttrId = TDevErAttributesForSrcAttrId;
	}

}
