package net.aicoder.exsys.module.entity;

// Generated 2015-10-31 11:27:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
//import javax.persistence.Version;

/**
 * TDevEntity generated by hbm2java
 */
@Entity
//@Table(name = "t_dev_entity", catalog = "db_jeap_dev", uniqueConstraints = @UniqueConstraint(columnNames = {
//		"sys_code", "mod_code", "code" }))
@Table(name = "t_dev_entity", uniqueConstraints = @UniqueConstraint(columnNames = {"sys_code", "mod_code", "code" }))
public class TDevEntity implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String id;
	private String devVersion;
	private TDevModule TDevModule;
	private String sysCode;
	private String modCode;
	private String code;
	private String name;
	private Integer seq;
	private String dbms;
	private String owner;
	private String status;
	private String phase;
	private String notes;
	private String CUid;
	private String CName;
	private Date CTime;
	private String MUid;
	private String MName;
	private Date MTime;
	private List<TDevEntRelation> TDevEntRelationsForDestEntId = new ArrayList<TDevEntRelation>(0);
	private List<TDevEntRelation> TDevEntRelationsForSrcEntId = new ArrayList<TDevEntRelation>(0);
	private List<TDevEntKey> TDevEntKeys = new ArrayList<TDevEntKey>(0);
	private List<TDevAttribute> TDevAttributes = new ArrayList<TDevAttribute>(0);

	public TDevEntity() {
	}

/*	public TDevEntity(String id, String sysCode, String code, String name) {
		this.id = id;
		this.sysCode = sysCode;
		this.code = code;
		this.name = name;
	}

	public TDevEntity(String id, TDevModule TDevModule, String sysCode,
			String modCode, String code, String name, Integer seq, String dbms,
			String owner, String status, String phase, String notes,
			String CUid, String CName, Date CTime, String MUid, String MName,
			Date MTime, List<TDevEntRelation> TDevEntRelationsForDestEntId,
			Set<TDevEntRelation> TDevEntRelationsForSrcEntId,
			Set<TDevEntKey> TDevEntKeys, List<TDevAttribute> TDevAttributes) {
		this.id = id;
		this.TDevModule = TDevModule;
		this.sysCode = sysCode;
		this.modCode = modCode;
		this.code = code;
		this.name = name;
		this.seq = seq;
		this.dbms = dbms;
		this.owner = owner;
		this.status = status;
		this.phase = phase;
		this.notes = notes;
		this.CUid = CUid;
		this.CName = CName;
		this.CTime = CTime;
		this.MUid = MUid;
		this.MName = MName;
		this.MTime = MTime;
		this.TDevEntRelationsForDestEntId = TDevEntRelationsForDestEntId;
		this.TDevEntRelationsForSrcEntId = TDevEntRelationsForSrcEntId;
		this.TDevEntKeys = TDevEntKeys;
		this.TDevAttributes = TDevAttributes;
	}*/

	@Id
	@GeneratedValue(generator = "paymentableGenerator")
	//@GenericGenerator(name = "paymentableGenerator", strategy = "uuid")
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


	@Column(name = "dev_version", length = 50)
	public String getDevVersion() {
		return this.devVersion;
	}

	public void setDevVersion(String devVersion) {
		this.devVersion = devVersion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mod_id")
	public TDevModule getTDevModule() {
		return this.TDevModule;
	}

	public void setTDevModule(TDevModule TDevModule) {
		this.TDevModule = TDevModule;
	}

	@Column(name = "sys_code", nullable = false, length = 50)
	public String getSysCode() {
		return this.sysCode;
	}

	public void setSysCode(String sysCode) {
		this.sysCode = sysCode;
	}

	@Column(name = "mod_code")
	public String getModCode() {
		return this.modCode;
	}

	public void setModCode(String modCode) {
		this.modCode = modCode;
	}

	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "seq")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "dbms", length = 50)
	public String getDbms() {
		return this.dbms;
	}

	public void setDbms(String dbms) {
		this.dbms = dbms;
	}

	@Column(name = "owner", length = 50)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "phase", length = 50)
	public String getPhase() {
		return this.phase;
	}

	public void setPhase(String phase) {
		this.phase = phase;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "c_uid", length = 50)
	public String getCUid() {
		return this.CUid;
	}

	public void setCUid(String CUid) {
		this.CUid = CUid;
	}

	@Column(name = "c_name", length = 50)
	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", length = 19)
	public Date getCTime() {
		return this.CTime;
	}

	public void setCTime(Date CTime) {
		this.CTime = CTime;
	}

	@Column(name = "m_uid", length = 50)
	public String getMUid() {
		return this.MUid;
	}

	public void setMUid(String MUid) {
		this.MUid = MUid;
	}

	@Column(name = "m_name", length = 50)
	public String getMName() {
		return this.MName;
	}

	public void setMName(String MName) {
		this.MName = MName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", length = 19)
	public Date getMTime() {
		return this.MTime;
	}

	public void setMTime(Date MTime) {
		this.MTime = MTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDevEntityByDestEntId")
	//@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	public List<TDevEntRelation> getTDevEntRelationsForDestEntId() {
		return this.TDevEntRelationsForDestEntId;
	}

	public void setTDevEntRelationsForDestEntId(
			List<TDevEntRelation> TDevEntRelationsForDestEntId) {
		this.TDevEntRelationsForDestEntId = TDevEntRelationsForDestEntId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDevEntityBySrcEntId")
	//@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	public List<TDevEntRelation> getTDevEntRelationsForSrcEntId() {
		return this.TDevEntRelationsForSrcEntId;
	}

	public void setTDevEntRelationsForSrcEntId(
			List<TDevEntRelation> TDevEntRelationsForSrcEntId) {
		this.TDevEntRelationsForSrcEntId = TDevEntRelationsForSrcEntId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDevEntity")
	//@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	public List<TDevEntKey> getTDevEntKeys() {
		return this.TDevEntKeys;
	}

	public void setTDevEntKeys( List<TDevEntKey> TDevEntKeys) {
		this.TDevEntKeys = TDevEntKeys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDevEntity")
	//@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	public List<TDevAttribute> getTDevAttributes() {
		return this.TDevAttributes;
	}

	public void setTDevAttributes( List<TDevAttribute> TDevAttributes) {
		this.TDevAttributes = TDevAttributes;
	}
}
