package net.aicoder.exsys.module.entity;

// Generated 2015-10-31 11:27:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TDevEntRelation generated by hbm2java
 */
@Entity
//@Table(name = "t_dev_ent_relation", catalog = "db_jeap_dev", uniqueConstraints = @UniqueConstraint(columnNames = {
//		"src_ent_id", "dest_ent_id", "id" }))
@Table(name = "t_dev_ent_relation", uniqueConstraints = @UniqueConstraint(columnNames = {"src_ent_id", "dest_ent_id", "id" }))
public class TDevEntRelation implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	

	private String id;
	private String type;
	//private Integer srcKeySeq;
	//private String destEntCode;
	private String srcKeyCode;
	private String destKeyCode;
	//private String srcKeyName;
	//private String destKeyName;
	private String srcMulti;
	private String destMulti;
	private String onDelete;
	private String onUpdate;
	private String notes;
	private String CUid;
	private String CName;
	private Date CTime;
	private String MUid;
	private String MName;
	private Date MTime;
	
	private List<TDevErAttribute> TDevErAttributes = new ArrayList<TDevErAttribute>(
			0);
	private TDevEntity TDevEntityByDestEntId;
	private TDevEntKey TDevEntKeyByDestKeyId;
	private TDevEntKey TDevEntKeyBySrcKeyId;
	private TDevEntity TDevEntityBySrcEntId;

	public TDevEntRelation() {
	}

/*	public TDevEntRelation(String id, TDevEntity TDevEntityByDestEntId,
			TDevEntKey TDevEntKeyBySrcKeyId, TDevEntity TDevEntityBySrcEntId,
			String type) {
		this.id = id;
		this.TDevEntityByDestEntId = TDevEntityByDestEntId;
		this.TDevEntKeyBySrcKeyId = TDevEntKeyBySrcKeyId;
		this.TDevEntityBySrcEntId = TDevEntityBySrcEntId;
		this.type = type;
	}

	public TDevEntRelation(String id, TDevEntity TDevEntityByDestEntId,
			TDevEntKey TDevEntKeyByDestKeyId, TDevEntKey TDevEntKeyBySrcKeyId,
			TDevEntity TDevEntityBySrcEntId, String type, String srcKeyCode,
			String destKeyCode, String srcMulti, String destMulti,
			String onDelete, String onUpdate, String notes, String CUid,
			String CName, Date CTime, String MUid, String MName, Date MTime,
			Set<TDevErAttribute> TDevErAttributes) {
		this.id = id;
		this.TDevEntityByDestEntId = TDevEntityByDestEntId;
		this.TDevEntKeyByDestKeyId = TDevEntKeyByDestKeyId;
		this.TDevEntKeyBySrcKeyId = TDevEntKeyBySrcKeyId;
		this.TDevEntityBySrcEntId = TDevEntityBySrcEntId;
		this.type = type;
		this.srcKeyCode = srcKeyCode;
		this.destKeyCode = destKeyCode;
		this.srcMulti = srcMulti;
		this.destMulti = destMulti;
		this.onDelete = onDelete;
		this.onUpdate = onUpdate;
		this.notes = notes;
		this.CUid = CUid;
		this.CName = CName;
		this.CTime = CTime;
		this.MUid = MUid;
		this.MName = MName;
		this.MTime = MTime;
		this.TDevErAttributes = TDevErAttributes;
	}*/

	@Id
	@GeneratedValue(generator = "paymentableGenerator")
	//@GenericGenerator(name = "paymentableGenerator", strategy = "uuid")
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dest_ent_id", nullable = false)
	public TDevEntity getTDevEntityByDestEntId() {
		return this.TDevEntityByDestEntId;
	}

	public void setTDevEntityByDestEntId(TDevEntity TDevEntityByDestEntId) {
		this.TDevEntityByDestEntId = TDevEntityByDestEntId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dest_key_id")
	public TDevEntKey getTDevEntKeyByDestKeyId() {
		return this.TDevEntKeyByDestKeyId;
	}

	public void setTDevEntKeyByDestKeyId(TDevEntKey TDevEntKeyByDestKeyId) {
		this.TDevEntKeyByDestKeyId = TDevEntKeyByDestKeyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "src_key_id", nullable = false)
	public TDevEntKey getTDevEntKeyBySrcKeyId() {
		return this.TDevEntKeyBySrcKeyId;
	}

	public void setTDevEntKeyBySrcKeyId(TDevEntKey TDevEntKeyBySrcKeyId) {
		this.TDevEntKeyBySrcKeyId = TDevEntKeyBySrcKeyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "src_ent_id", nullable = false)
	public TDevEntity getTDevEntityBySrcEntId() {
		return this.TDevEntityBySrcEntId;
	}

	public void setTDevEntityBySrcEntId(TDevEntity TDevEntityBySrcEntId) {
		this.TDevEntityBySrcEntId = TDevEntityBySrcEntId;
	}

	@Column(name = "type", nullable = false, length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
/*
	@Column(name = "src_key_seq")
	public Integer getSrcKeySeq() {
		return srcKeySeq;
	}

	public void setSrcKeySeq(Integer srcKeySeq) {
		this.srcKeySeq = srcKeySeq;
	}
*/
	/**
	@Column(name = "dest_ent_code", length = 50)
	public String getDestEntCode() {
		return destEntCode;
	}

	public void setDestEntCode(String destEntCode) {
		this.destEntCode = destEntCode;
	}
	**/

	@Column(name = "src_key_code", length = 50)
	public String getSrcKeyCode() {
		return this.srcKeyCode;
	}

	public void setSrcKeyCode(String srcKeyCode) {
		this.srcKeyCode = srcKeyCode;
	}

	@Column(name = "dest_key_code", length = 50)
	public String getDestKeyCode() {
		return this.destKeyCode;
	}

	public void setDestKeyCode(String destKeyCode) {
		this.destKeyCode = destKeyCode;
	}
/*
	@Column(name = "src_key_name", length = 50)
	public String getSrcKeyName() {
		return this.srcKeyName;
	}

	public void setSrcKeyName(String srcKeyName) {
		this.srcKeyName = srcKeyName;
	}
*/	

/*	
	@Column(name = "dest_key_name", length = 50)
	public String getDestKeyName() {
		return this.destKeyName;
	}

	public void setDestKeyName(String destKeyName) {
		this.destKeyName = destKeyName;
	}
*/
	@Column(name = "src_multi", length = 10)
	public String getSrcMulti() {
		return this.srcMulti;
	}

	public void setSrcMulti(String srcMulti) {
		this.srcMulti = srcMulti;
	}

	@Column(name = "dest_multi", length = 10)
	public String getDestMulti() {
		return this.destMulti;
	}

	public void setDestMulti(String destMulti) {
		this.destMulti = destMulti;
	}

	@Column(name = "on_delete", length = 10)
	public String getOnDelete() {
		return this.onDelete;
	}

	public void setOnDelete(String onDelete) {
		this.onDelete = onDelete;
	}

	@Column(name = "on_update", length = 10)
	public String getOnUpdate() {
		return this.onUpdate;
	}

	public void setOnUpdate(String onUpdate) {
		this.onUpdate = onUpdate;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "c_uid", length = 50)
	public String getCUid() {
		return this.CUid;
	}

	public void setCUid(String CUid) {
		this.CUid = CUid;
	}

	@Column(name = "c_name", length = 50)
	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", length = 19)
	public Date getCTime() {
		return this.CTime;
	}

	public void setCTime(Date CTime) {
		this.CTime = CTime;
	}

	@Column(name = "m_uid", length = 50)
	public String getMUid() {
		return this.MUid;
	}

	public void setMUid(String MUid) {
		this.MUid = MUid;
	}

	@Column(name = "m_name", length = 50)
	public String getMName() {
		return this.MName;
	}

	public void setMName(String MName) {
		this.MName = MName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", length = 19)
	public Date getMTime() {
		return this.MTime;
	}

	public void setMTime(Date MTime) {
		this.MTime = MTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDevEntRelation")
	//@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	public List<TDevErAttribute> getTDevErAttributes() {
		return this.TDevErAttributes;
	}

	public void setTDevErAttributes( List<TDevErAttribute> TDevErAttributes) {
		this.TDevErAttributes = TDevErAttributes;
	}

}
